#
# PROGRAM:	Assignment 3
# PROGRAMMER: 	VICTOR PADILLA
#

CC = g++
CCFLAGS = -Wall -std=c++11

Assign2: Assignment3.o
	$(CC) $(CCFLAGS) -o z1689628_A3 Assignment3.o

Assignment2.o: Assignment3.cpp
	$(CC) $(CCFLAGS) -c Assignment3.cpp

clean:
	-rm *.o
