#
#  PROGRAM:   assign8
#  AUTHOR:    Victor Padilla
#  LOGON ID:  z1689628
#  DUE DATE:  4/18/2016
#
CC = g++
CCFLAGS = -Wall -O
ASSIGN = assignment8
CLASS1 = assignment8
	
$(ASSIGN) : $(ASSIGN).o $(CLASS1).o
	$(CC) $(CCFLAGS) -o $(ASSIGN) $(ASSIGN).o $(CLASS1).o -lm

$(ASSIGN).o : $(CLASS1).h	$(CC) -c $(ASSIGN).cc

clean :
	- rm *.o
	- rm $(ASSIGN)

