#
#  PROGRAM:   assign9
#  AUTHOR:    Victor Padilla
#  LOGON ID:  z1689628
#  DUE DATE:  5/2/16
#
CC = g++
CCFLAGS = -Wall -O
ASSIGN = assignment9
CLASS1 = assignment9
	
$(ASSIGN) : $(ASSIGN).o 
	g++ -Wall -g assignment9.cc -o assignment9


clean :
	- rm *.o
	- rm $(ASSIGN)
